data_file = 'data/LLCP2021.XPT'
best_cols = ['CVDSTRK3',
             'LANDSEX',
             'GENHLTH',
             'PHYSHLTH',
             'MENTHLTH',
             'EXERANY2',
             'ASTHMA3',
             'CHCSCNCR',
             'CHCKDNY2',
             'DIABETE4',
             'SMOKDAY2',
             '_PRACE1',
             '_BMI5CAT']

best_cols_rename = {
    'CVDSTRK3': "stroke",
    'LANDSEX': "sex",
    'GENHLTH': "general_health",
    'PHYSHLTH': "bad_physical_health_30d",
    'MENTHLTH': "bad_mental_health_30d",
    'EXERANY2': "exercise_30d",
    'ASTHMA3': "asthma",
    'CHCSCNCR': "skin_cancer",
    'CHCKDNY2': "kidney_disease",
    'DIABETE4': "diabetes",
    'SMOKDAY2': "smoking_habbit",
    'X_PRACE1': "race",
    # '_BMI5CAT': "bmi_category",
    'X_BMI5CAT': 'bmi_category',
    'CVDCRHD4': "is_chd"
}

model_file = "model/CHD_model.sav"

# Based on the Data Dictionary below are the Categorical and Continuous variables
categorical_vars = ['_AGE_G', '_AGE65YR', '_AGEG5YR', '_DRDXAR3', '_LMTACT3', '_BMI5CAT', '_LMTWRK3',
                    '_CHISPNC', '_CHLDCNT', 'ARTHDIS2', '_CLLCPWT', '_CPRACE1', '_CRACE1', '_CURECI1',
                    'ARTHEDU', '_DUALCOR', '_DUALUSE', '_EDUCAG', '_FLSHOT7', '_FRT16A', '_FRTLT1A',
                    '_FRTRES1', '_FRUITE1', '_HCVU652', '_HISPANC', '_HLTHPLN', '_IMPRACE', '_INCOMG1',
                    'ARTHEXER', 'HAVARTH5', 'JOINPAI2', 'LMTJOIN3', '_METSTAT', '_ASTHMS1', '_MISFRT1',
                    '_MISVEG1', '_MRACE1', '_PHYS14D', '_PNEUMO3', '_PRACE1', '_RACE', '_RACEG21', '_RACEGR3',
                    '_RACEPRV', '_RAWRAKE', '_RFBING5', '_RFBMI5', '_CASTHM1', '_RFDRHV7', '_RFHLTH',
                    '_LTASTH1', '_RFSMOK3', '_SEX', '_SMOKER3', '_STRWT', '_TOTINDA', '_URBSTAT', '_VEG23A',
                    '_VEGETE1', '_VEGLT1A', '_VEGRES1', '_WT2RAKE', 'ACEADNED', 'ACEADSAF', 'ACEDEPRS',
                    'ACEDIVRC', 'ACEDRINK', 'ACEDRUGS', 'ACEHURT1', 'ACEHVSEX', 'ACEPRISN', 'ACEPUNCH',
                    'ACESWEAR', 'ACETOUCH', 'ACETTHEM', 'ASTHMA3', 'ASTHNOW', 'CASTHDX2', 'BLDSTFIT',
                    'CERVSCRN', 'CHCOCNCR', 'BIRTHSEX', 'CHCSCNCR', 'CNCRDIFF', 'COLNCNCR', 'CADULT1',
                    'CAGEG', 'CAREGIV1', 'COLNSIGM', 'CASTHNO2', 'CCLGHOUS', 'COLNTES1', 'CRVCLCNC',
                    'CRVCLHPV', 'CRVCLPAP', 'CSRVCLIN', 'CELLFON5', 'CELLSEX', 'CELPHON1', 'CSRVCTL2',
                    'CSRVDEIN', 'CSRVDOC1', 'CSRVINSR', 'CSRVINST', 'CHECKUP1', 'CSRVPAIN', 'CSRVRTRN',
                    'CSRVSUM', 'CSRVTRT3', 'HADHYST2', 'HADMAM', 'HADSIGM4', 'COLGHOUS', 'COLGSEX',
                    'HOWLONG', 'LASTSIG4', 'LCSCTSCN', 'CPDEMO1B', 'CRGVALZD', 'CRGVEXPT', 'CRGVHOU1',
                    'CRGVHRS1', 'CRGVLNG1', 'CRGVPER1', 'CRGVPRB3', 'CRGVREL4', 'PCPSARS2', 'PCSTALK',
                    'PSATEST1', 'PSATIME1', 'SDNATES1', 'SIGMTES1', 'SMALSTOL', 'STOLTEST', 'STOOLDN1',
                    'VCLNTES1', 'VIRCOLO1', '_MICHD', 'CSTATE1', 'CTELENM1', 'CTELNUM1', 'CVDINFR4',
                    'CDASSIST', 'CDDISCUS', 'CDHELP', 'CDHOUSE', 'CDSOCIAL', '_CHOLCH3', '_RFCHOL3', '_RFHYPE6',
                    'DIFFALON', 'BPHIGH6', 'BPMEDS', 'DISPCODE', 'CHOLCHK3', 'CHOLMED3', 'DRNKANY5', 'ECIGNOW1',
                    'EDUCA', 'EMPLOY1', 'EXERANY2', 'CVDSTRK3', 'DRADVISE', 'HOMBPCHK', 'FIREARM5', 'FLUSHOT7',
                    'FMONTH', 'GENHLTH', 'GUNLOAD', 'HOMRGCHK', 'SHAREBP', 'TOLDHI3', 'WHEREBP', 'DIABEDU',
                    'DIABETE4', 'DIABEYE', 'INSULIN1', 'PDIABTST', 'PREDIAB1', 'HPVADSHT', 'HPVADVC4', 'IMFVPLA2',
                    'IMONTH', 'INCOME3', 'HAVECFS', 'IYEAR', 'TOLDCFS', 'LADULT1', 'LANDLINE', 'LANDSEX', 'DEAF',
                    'LASTSMK2', 'HAVEHEPB', 'HAVEHEPC', 'LOADULK2', 'MARITAL', 'MEDCOST1', 'MEDSHEPB', 'PRIRHEPC',
                    'MSCODE', 'NUMADULT', 'NUMHHOL3', 'NUMMEN', 'NUMPHON3', 'NUMWOMEN', 'TOLDHEPC', 'TRETHEPC',
                    '_AIDTST4', 'PERSDOC3', 'PNEUVAC4', 'HIVTST7', 'PREGNANT', 'PRIMINSR', 'CHCKDNY2', '_MENT14D',
                    'ADDEPEV3', 'PVTRESD1', 'PVTRESD3', 'QSTLANG', 'QSTVER', 'RCSGENDR', 'RCSRLTN2', 'RENTHOM1',
                    'RESPSLCT', 'RSNMRJN2', 'SAFETIME', 'CIMEMLOS', 'SEXVAR', 'DECIDE', 'SHINGLE2', 'SMOKDAY2',
                    'SMOKE100', 'SOFEMALE', 'SOMALE', 'STATERE1', 'DIFFDRES', 'DIFFWALK', 'STOPSMK2', 'TETANUS1',
                    'CHCCOPD3', 'TRNSGNDR', 'USEMRJN3', 'USENOW3', 'VETERAN3', 'BLIND', 'EYEEXAM1', 'WORKCFS',
                    'WTCHSALT',
                    'CVDCRHD4'
                    ]

continuous_vars = ['_AGE80', '_BMI5', '_DRNKWK1', '_FRUTSU1', '_PSU', '_STATE', '_STSTR', '_VEGESU1', 'ALCDAY5',
                   'AVEDRNK3', 'CNCRAGE', 'CNCRTYP1', 'CHILDREN', 'DRNK3GE5', 'DROCDY3_', 'FLSHTMY3', 'FRENCHF1',
                   'FRNCHDA_', 'FRUIT2', 'FRUITJU2', 'FRUTDA2_', 'FTJUDA2_', 'FVGREEN1', 'GRENDA1_', 'DIABAGE3',
                   'HEIGHT3', 'HHADULT', 'DOCTDIAB', 'HTIN4', 'HTM4', 'IDATE', 'IDAY', 'LCSFIRST', 'LCSLAST',
                   'LCSNUMCG', 'MARIJAN1', 'MAXDRNKS', 'PHYSHLTH', 'POTADA1_', 'POTATOE1', 'HIVTSTD3', 'SEQNO',
                   'MENTHLTH', 'POORHLTH', 'BLDSUGAR', 'CHKHEMO3', 'FEETCHK', 'FEETCHK3', 'VEGEDA2_', 'VEGETAB2',
                   'WEIGHT2', 'WTKG3']
disease_dict = {
    'stroke': {1: 'Yes', 2: 'No', 99: 'Other'},
    'sex': {1: 'Male', 2: 'Female', 99: 'Other'},
    # general_health={ 1:,2:,3:,4:,5:,7:,9:},
    'exercise_30d': {1: 'Yes', 2: 'No', 99: 'Other'},
    'asthma': {1: 'Yes', 2: 'No', 99: 'Other'},
    'skin_cancer': {1: 'Yes', 2: 'No', 99: 'Other'},
    'kidney_disease': {1: 'Yes', 2: 'No', 99: 'Other'},
    'diabetes': {1: 'Yes', 2: 'Yes', 3: 'No', 4: 'No', 99: 'Other'},
    'smoking_habbit': {1: 'Every day', 2: 'Some days', 3: 'Not at all', 99: 'Other'}
}
